using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokemonGameInfo.Helpers
{
    public class Constants
    {
        public const string LuisSubscriptionKey = "e58700e5492f4d89aa3b99749be3f9df";
        public const string ExamplePNG = "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/131.png";

        public const string LuisIdRoot = "70300c18-fe86-490c-9dd5-3f08176042c7";

        public static Dictionary<int, string> PokemonNames = new Dictionary<int, string>();
        static Constants() {
            PokemonNames.Add(1, "Bulbasaur");
            PokemonNames.Add(2, "Ivysaur");
            PokemonNames.Add(3, "Venusaur");
            PokemonNames.Add(4, "Charmander");
            PokemonNames.Add(5, "Charmeleon");
            PokemonNames.Add(6, "Charizard");
            PokemonNames.Add(7, "Squirtle");
            PokemonNames.Add(8, "Wartortle");
            PokemonNames.Add(9, "Blastoise");
            PokemonNames.Add(10, "Caterpie");
            PokemonNames.Add(11, "Metapod");
            PokemonNames.Add(12, "Butterfree");
            PokemonNames.Add(13, "Weedle");
            PokemonNames.Add(14, "Kakuna");
            PokemonNames.Add(15, "Beedrill");
            PokemonNames.Add(16, "Pidgey");
            PokemonNames.Add(17, "Pidgeotto");
            PokemonNames.Add(18, "Pidgeot");
            PokemonNames.Add(19, "Rattata");
            PokemonNames.Add(20, "Raticate");
            PokemonNames.Add(21, "Spearow");
            PokemonNames.Add(22, "Fearow");
            PokemonNames.Add(23, "Ekans");
            PokemonNames.Add(24, "Arbok");
            PokemonNames.Add(25, "Pikachu");
            PokemonNames.Add(26, "Raichu");
            PokemonNames.Add(27, "Sandshrew");
            PokemonNames.Add(28, "Sandslash");
            PokemonNames.Add(29, "Nidoran");
            PokemonNames.Add(30, "Nidorina");
            PokemonNames.Add(31, "Nidoqueen");
            PokemonNames.Add(32, "Nidoran");
            PokemonNames.Add(33, "Nidorino");
            PokemonNames.Add(34, "Nidoking");
            PokemonNames.Add(35, "Clefairy");
            PokemonNames.Add(36, "Clefable");
            PokemonNames.Add(37, "Vulpix");
            PokemonNames.Add(38, "Ninetales");
            PokemonNames.Add(39, "Jigglypuff");
            PokemonNames.Add(40, "Wigglytuff");
            PokemonNames.Add(41, "Zubat");
            PokemonNames.Add(42, "Golbat");
            PokemonNames.Add(43, "Oddish");
            PokemonNames.Add(44, "Gloom");
            PokemonNames.Add(45, "Vileplume");
            PokemonNames.Add(46, "Paras");
            PokemonNames.Add(47, "Parasect");
            PokemonNames.Add(48, "Venonat");
            PokemonNames.Add(49, "Venomoth");
            PokemonNames.Add(50, "Diglett");
            PokemonNames.Add(51, "Dugtrio");
            PokemonNames.Add(52, "Meowth");
            PokemonNames.Add(53, "Persian");
            PokemonNames.Add(54, "Psyduck");
            PokemonNames.Add(55, "Golduck");
            PokemonNames.Add(56, "Mankey");
            PokemonNames.Add(57, "Primeape");
            PokemonNames.Add(58, "Growlithe");
            PokemonNames.Add(59, "Arcanine");
            PokemonNames.Add(60, "Poliwag");
            PokemonNames.Add(61, "Poliwhirl");
            PokemonNames.Add(62, "Poliwrath");
            PokemonNames.Add(63, "Abra");
            PokemonNames.Add(64, "Kadabra");
            PokemonNames.Add(65, "Alakazam");
            PokemonNames.Add(66, "Machop");
            PokemonNames.Add(67, "Machoke");
            PokemonNames.Add(68, "Machamp");
            PokemonNames.Add(69, "Bellsprout");
            PokemonNames.Add(70, "Weepinbell");
            PokemonNames.Add(71, "Victreebel");
            PokemonNames.Add(72, "Tentacool");
            PokemonNames.Add(73, "Tentacruel");
            PokemonNames.Add(74, "Geodude");
            PokemonNames.Add(75, "Graveler");
            PokemonNames.Add(76, "Golem");
            PokemonNames.Add(77, "Ponyta");
            PokemonNames.Add(78, "Rapidash");
            PokemonNames.Add(79, "Slowpoke");
            PokemonNames.Add(80, "Slowbro");
            PokemonNames.Add(81, "Magnemite");
            PokemonNames.Add(82, "Magneton");
            PokemonNames.Add(83, "Farfetch'd");
            PokemonNames.Add(84, "Doduo");
            PokemonNames.Add(85, "Dodrio");
            PokemonNames.Add(86, "Seel");
            PokemonNames.Add(87, "Dewgong");
            PokemonNames.Add(88, "Grimer");
            PokemonNames.Add(89, "Muk");
            PokemonNames.Add(90, "Shellder");
            PokemonNames.Add(91, "Cloyster");
            PokemonNames.Add(92, "Gastly");
            PokemonNames.Add(93, "Haunter");
            PokemonNames.Add(94, "Gengar");
            PokemonNames.Add(95, "Onix");
            PokemonNames.Add(96, "Drowzee");
            PokemonNames.Add(97, "Hypno");
            PokemonNames.Add(98, "Krabby");
            PokemonNames.Add(99, "Kingler");
            PokemonNames.Add(100, "Voltorb");
            PokemonNames.Add(101, "Electrode");
            PokemonNames.Add(102, "Exeggcute");
            PokemonNames.Add(103, "Exeggutor");
            PokemonNames.Add(104, "Cubone");
            PokemonNames.Add(105, "Marowak");
            PokemonNames.Add(106, "Hitmonlee");
            PokemonNames.Add(107, "Hitmonchan");
            PokemonNames.Add(108, "Lickitung");
            PokemonNames.Add(109, "Koffing");
            PokemonNames.Add(110, "Weezing");
            PokemonNames.Add(111, "Rhyhorn");
            PokemonNames.Add(112, "Rhydon");
            PokemonNames.Add(113, "Chansey");
            PokemonNames.Add(114, "Tangela");
            PokemonNames.Add(115, "Kangaskhan");
            PokemonNames.Add(116, "Horsea");
            PokemonNames.Add(117, "Seadra");
            PokemonNames.Add(118, "Goldeen");
            PokemonNames.Add(119, "Seaking");
            PokemonNames.Add(120, "Staryu");
            PokemonNames.Add(121, "Starmie");
            PokemonNames.Add(122, "Mr Mime");
            PokemonNames.Add(123, "Scyther");
            PokemonNames.Add(124, "Jynx");
            PokemonNames.Add(125, "Electabuzz");
            PokemonNames.Add(126, "Magmar");
            PokemonNames.Add(127, "Pinsir");
            PokemonNames.Add(128, "Tauros");
            PokemonNames.Add(129, "Magikarp");
            PokemonNames.Add(130, "Gyarados");
            PokemonNames.Add(131, "Lapras");
            PokemonNames.Add(132, "Ditto");
            PokemonNames.Add(133, "Eevee");
            PokemonNames.Add(134, "Vaporeon");
            PokemonNames.Add(135, "Jolteon");
            PokemonNames.Add(136, "Flareon");
            PokemonNames.Add(137, "Porygon");
            PokemonNames.Add(138, "Omanyte");
            PokemonNames.Add(139, "Omastar");
            PokemonNames.Add(140, "Kabuto");
            PokemonNames.Add(141, "Kabutops");
            PokemonNames.Add(142, "Aerodactyl");
            PokemonNames.Add(143, "Snorlax");
            PokemonNames.Add(144, "Articuno");
            PokemonNames.Add(145, "Zapdos");
            PokemonNames.Add(146, "Moltres");
            PokemonNames.Add(147, "Dratini");
            PokemonNames.Add(148, "Dragonair");
            PokemonNames.Add(149, "Dragonite");
            PokemonNames.Add(150, "Mewtwo");
            PokemonNames.Add(151, "Mew");
        }

    }            
            
}